//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItTakesAVillage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ItTakesAVillage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Låna.
        /// </summary>
        public static string Borrow {
            get {
                return ResourceManager.GetString("Borrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utlånad.
        /// </summary>
        public static string Borrowed {
            get {
                return ResourceManager.GetString("Borrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fyll i formuläret för att låna.
        /// </summary>
        public static string BorrowTitleFormular {
            get {
                return ResourceManager.GetString("BorrowTitleFormular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ändra beskrivning?.
        /// </summary>
        public static string ChangeDescription {
            get {
                return ResourceManager.GetString("ChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ändra meddelandet?.
        /// </summary>
        public static string ChangeMessage {
            get {
                return ResourceManager.GetString("ChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ändra namn?.
        /// </summary>
        public static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stäng.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa ny grupp.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa en grupp för att dela prylar!.
        /// </summary>
        public static string CreateGroupText {
            get {
                return ResourceManager.GetString("CreateGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivning: .
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fyll i dina ändringar.
        /// </summary>
        public static string EditTitleFormular {
            get {
                return ResourceManager.GetString("EditTitleFormular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Från vilket datum?.
        /// </summary>
        public static string FromDateText {
            get {
                return ResourceManager.GetString("FromDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meddelande.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meddelande:.
        /// </summary>
        public static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inget meddelande.
        /// </summary>
        public static string NoMessage {
            get {
                return ResourceManager.GetString("NoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finns inga delade prylar.
        /// </summary>
        public static string NoSharedTools {
            get {
                return ResourceManager.GetString("NoSharedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i gruppen.
        /// </summary>
        public static string OfGroup {
            get {
                return ResourceManager.GetString("OfGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delad av.
        /// </summary>
        public static string SharedOf {
            get {
                return ResourceManager.GetString("SharedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delad av:.
        /// </summary>
        public static string SharedOfText {
            get {
                return ResourceManager.GetString("SharedOfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Börja dela med dina vänner.
        /// </summary>
        public static string ShareToolText {
            get {
                return ResourceManager.GetString("ShareToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till vilket datum?.
        /// </summary>
        public static string ToDateText {
            get {
                return ResourceManager.GetString("ToDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prylpool.
        /// </summary>
        public static string ToolPool {
            get {
                return ResourceManager.GetString("ToolPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prylnamn:.
        /// </summary>
        public static string ToolText {
            get {
                return ResourceManager.GetString("ToolText", resourceCulture);
            }
        }
    }
}
