//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItTakesAVillage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ItTakesAVillage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ange en beskrvning?.
        /// </summary>
        public static string AddDescription {
            get {
                return ResourceManager.GetString("AddDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du lägga till en bild?.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till medlem i grupp.
        /// </summary>
        public static string AddMember {
            get {
                return ResourceManager.GetString("AddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg upp en pryl.
        /// </summary>
        public static string AddTool {
            get {
                return ResourceManager.GetString("AddTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afrikanskt ordspråk.
        /// </summary>
        public static string AfricanProverb {
            get {
                return ResourceManager.GetString("AfricanProverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hos.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillbaka till dina grupper.
        /// </summary>
        public static string BackToGroup {
            get {
                return ResourceManager.GetString("BackToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Låna.
        /// </summary>
        public static string Borrow {
            get {
                return ResourceManager.GetString("Borrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Låna något från prylpoolen.
        /// </summary>
        public static string BorrowATool {
            get {
                return ResourceManager.GetString("BorrowATool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utlånad.
        /// </summary>
        public static string Borrowed {
            get {
                return ResourceManager.GetString("Borrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lånad:.
        /// </summary>
        public static string BorrowedDateText {
            get {
                return ResourceManager.GetString("BorrowedDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fyll i formuläret för att låna.
        /// </summary>
        public static string BorrowTitleFormular {
            get {
                return ResourceManager.GetString("BorrowTitleFormular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ändra beskrivning?.
        /// </summary>
        public static string ChangeDescription {
            get {
                return ResourceManager.GetString("ChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ändra meddelandet?.
        /// </summary>
        public static string ChangeMessage {
            get {
                return ResourceManager.GetString("ChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du ändra namn?.
        /// </summary>
        public static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj grupp.
        /// </summary>
        public static string ChooseGroup {
            get {
                return ResourceManager.GetString("ChooseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stäng.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string ColonSign {
            get {
                return ResourceManager.GetString("ColonSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapat datum.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa ny matlagsinbjudan.
        /// </summary>
        public static string CreateDinnerInvitation {
            get {
                return ResourceManager.GetString("CreateDinnerInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa en ny grupp.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa en grupp för att bjuda in till matlag!.
        /// </summary>
        public static string CreateGroupDinner {
            get {
                return ResourceManager.GetString("CreateGroupDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa en grupp för att bjuda in till lekträff!.
        /// </summary>
        public static string CreateGroupPlayDate {
            get {
                return ResourceManager.GetString("CreateGroupPlayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa en grupp för att dela prylar!.
        /// </summary>
        public static string CreateGroupText {
            get {
                return ResourceManager.GetString("CreateGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa ny lekträffsinbjudan.
        /// </summary>
        public static string CreatePlayDate {
            get {
                return ResourceManager.GetString("CreatePlayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivning.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matlag.
        /// </summary>
        public static string DinnerInvitation {
            get {
                return ResourceManager.GetString("DinnerInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redigera.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fyll i dina ändringar.
        /// </summary>
        public static string EditTitleFormular {
            get {
                return ResourceManager.GetString("EditTitleFormular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to för.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Från vilket datum?.
        /// </summary>
        public static string FromDateText {
            get {
                return ResourceManager.GetString("FromDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samla dina vänner och börja hjälpas åt!.
        /// </summary>
        public static string GatherFriends {
            get {
                return ResourceManager.GetString("GatherFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå till grupp.
        /// </summary>
        public static string GoToGroup {
            get {
                return ResourceManager.GetString("GoToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppchatt.
        /// </summary>
        public static string GroupChat {
            get {
                return ResourceManager.GetString("GroupChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange gruppens namn.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupper.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kom igång idag och skapa en grupp!.
        /// </summary>
        public static string GroupToday {
            get {
                return ResourceManager.GetString("GroupToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inbjudan.
        /// </summary>
        public static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boka in lekträff.
        /// </summary>
        public static string InvitePlayDate {
            get {
                return ResourceManager.GetString("InvitePlayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bjud in din grupp till matlag.
        /// </summary>
        public static string InviteToDinner {
            get {
                return ResourceManager.GetString("InviteToDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga ut.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jag.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medlemmar.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meddelande.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitt konto.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mina grupper.
        /// </summary>
        public static string MyGroups {
            get {
                return ResourceManager.GetString("MyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behöver du skapa en ny grupp?.
        /// </summary>
        public static string NeedCreateGroup {
            get {
                return ResourceManager.GetString("NeedCreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har inga lånade prylar.
        /// </summary>
        public static string NoBorrowedTools {
            get {
                return ResourceManager.GetString("NoBorrowedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga händelser har skapats i din grupp.
        /// </summary>
        public static string NoEvents {
            get {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inget meddelande.
        /// </summary>
        public static string NoMessage {
            get {
                return ResourceManager.GetString("NoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finns inga delade prylar.
        /// </summary>
        public static string NoSharedTools {
            get {
                return ResourceManager.GetString("NoSharedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingenting på gång just nu...
        /// </summary>
        public static string NothingOnGoing {
            get {
                return ResourceManager.GetString("NothingOnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i gruppen.
        /// </summary>
        public static string OfGroup {
            get {
                return ResourceManager.GetString("OfGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to På gång.
        /// </summary>
        public static string OnGoing {
            get {
                return ResourceManager.GetString("OnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Övrig information.
        /// </summary>
        public static string OtherInfo {
            get {
                return ResourceManager.GetString("OtherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekträff.
        /// </summary>
        public static string PlayDate {
            get {
                return ResourceManager.GetString("PlayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekträffar.
        /// </summary>
        public static string PlayDates {
            get {
                return ResourceManager.GetString("PlayDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrera.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatorigska fält.
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Återlämnas:.
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Återlämna.
        /// </summary>
        public static string ReturnText {
            get {
                return ResourceManager.GetString("ReturnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skicka.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delad av.
        /// </summary>
        public static string SharedOf {
            get {
                return ResourceManager.GetString("SharedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delade prylar.
        /// </summary>
        public static string SharedTools {
            get {
                return ResourceManager.GetString("SharedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dela pryl.
        /// </summary>
        public static string ShareTool {
            get {
                return ResourceManager.GetString("ShareTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Börja dela med dina vänner.
        /// </summary>
        public static string ShareToolText {
            get {
                return ResourceManager.GetString("ShareToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv ett meddelande och börja kommunicera med dina vänner.
        /// </summary>
        public static string StartChat {
            get {
                return ResourceManager.GetString("StartChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till vilket datum?.
        /// </summary>
        public static string ToDateText {
            get {
                return ResourceManager.GetString("ToDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idag.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pryl.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prylpool.
        /// </summary>
        public static string ToolPool {
            get {
                return ResourceManager.GetString("ToolPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prylar.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prylnamn.
        /// </summary>
        public static string ToolText {
            get {
                return ResourceManager.GetString("ToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;It takes a village to raise a child&quot;.
        /// </summary>
        public static string VillageQuote {
            get {
                return ResourceManager.GetString("VillageQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vad ska du bjuda på?.
        /// </summary>
        public static string WhatInvite {
            get {
                return ResourceManager.GetString("WhatInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vad bjuds det på?.
        /// </summary>
        public static string WhatsOnMenu {
            get {
                return ResourceManager.GetString("WhatsOnMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to När.
        /// </summary>
        public static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Var.
        /// </summary>
        public static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Var ska ni vara?.
        /// </summary>
        public static string WhereBe {
            get {
                return ResourceManager.GetString("WhereBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vilket datum och tid?*.
        /// </summary>
        public static string WhichDateTime {
            get {
                return ResourceManager.GetString("WhichDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vilken grupp?*.
        /// </summary>
        public static string WhichGroup {
            get {
                return ResourceManager.GetString("WhichGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vilken pryl?*.
        /// </summary>
        public static string WhichTool {
            get {
                return ResourceManager.GetString("WhichTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vem vill leka?.
        /// </summary>
        public static string WhoPlay {
            get {
                return ResourceManager.GetString("WhoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vilka ska leka.
        /// </summary>
        public static string WhoPlays {
            get {
                return ResourceManager.GetString("WhoPlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vem vill barnet leka med?.
        /// </summary>
        public static string WithPlay {
            get {
                return ResourceManager.GetString("WithPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to din.
        /// </summary>
        public static string Your {
            get {
                return ResourceManager.GetString("Your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dina lånade prylar.
        /// </summary>
        public static string YourBorrowed {
            get {
                return ResourceManager.GetString("YourBorrowed", resourceCulture);
            }
        }
    }
}
